pipelines:

  - name: test_dynamic_node
    configuration:  
      runtime:       
        type: image
        image:
          custom:
            name: ubuntu
            tag: latest
            registry: ranjan_aws
            region: us-east-1
    steps:
      - name: matrix_test2
        type: Matrix
        stepMode: Bash
        configuration:
          nodePool: c7dynamic #u16dynamic
        stepletMultipliers:
          environmentVariables:
            - env1: one
              env2: two
#               env3: three
#             - env1: changed1
#               env2: changed2
#             - key_1: value1
#               key_2: value2
#           runtimes:
#             - type: image
#               image:
#                 auto:
#                   language: java
#                   versions:
#                     - 13
               
#             - type: image
#               image:
#                 auto:
#                   language: java
#                   versions:
#                     - 11
                    
#             - type: image
#               image:
#                 auto:
#                   language: java
#                   versions:
#                     - 8
                    
#             - type: image
#               image:
#                 auto:
#                   language: node
#                   versions:
#                     - 8.17.0
                    
#             - type: image
#               image:
#                 auto:
#                   language: node
#                   versions:
#                     - 10.18.0
                    
#             - type: image
#               image:
#                 auto:
#                   language: node
#                   versions:
#                     - 12.14.0
                    
#             - type: image
#               image:
#                 auto:
#                   language: cpp
#                   versions:
#                     - 8.0.0 
                    
#             - type: image
#               image:
#                 auto:
#                   language: cpp
#                   versions:
#                     - 9.0.0
                    
#             - type: image
#               image:
#                 auto:
#                   language: go
#                   versions:
#                     - 1.11.13 
                    
#             - type: image
#               image:
#                 auto:
#                   language: go
#                   versions:
#                     - 1.13.7 
                    
#             - type: image
#               image:
#                 auto:
#                   language: go
#                   versions:
#                     - 1.12.14        
        execution:
          onExecute:
            - echo "I am on matrix step"
