pipelines:

  - name: test
    configuration:  
      runtime:       
        type: image
        image:
          custom:
            name: ubuntu
            tag: latest
            registry: i_aws
            region: us-east-1
    steps:
      - name: testaws
        type: Bash
        execution:
          onExecute:
            - printenv
            - |
              [ $step_image_name == ubuntu ] 
            - |
              [ $step_image_tag == latest ]
